/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCachacaRouteImport } from './routes/_authenticated/cachaca'
import { Route as AuthenticatedComidaRouteImport } from './routes/_authenticated/comida'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedOutrasReceitasRouteImport } from './routes/_authenticated/outras-receitas'
import { Route as AuthenticatedOutrosRouteImport } from './routes/_authenticated/outros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCachacaRoute = AuthenticatedCachacaRouteImport.update({
  id: '/cachaca',
  path: '/cachaca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComidaRoute = AuthenticatedComidaRouteImport.update({
  id: '/comida',
  path: '/comida',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutrasReceitasRoute =
  AuthenticatedOutrasReceitasRouteImport.update({
    id: '/outras-receitas',
    path: '/outras-receitas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutrosRoute = AuthenticatedOutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cachaca': typeof AuthenticatedCachacaRoute
  '/comida': typeof AuthenticatedComidaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/outras-receitas': typeof AuthenticatedOutrasReceitasRoute
  '/outros': typeof AuthenticatedOutrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cachaca': typeof AuthenticatedCachacaRoute
  '/comida': typeof AuthenticatedComidaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/outras-receitas': typeof AuthenticatedOutrasReceitasRoute
  '/outros': typeof AuthenticatedOutrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cachaca': typeof AuthenticatedCachacaRoute
  '/_authenticated/comida': typeof AuthenticatedComidaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/outras-receitas': typeof AuthenticatedOutrasReceitasRoute
  '/_authenticated/outros': typeof AuthenticatedOutrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cachaca'
    | '/comida'
    | '/dashboard'
    | '/lancamentos'
    | '/outras-receitas'
    | '/outros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cachaca'
    | '/comida'
    | '/dashboard'
    | '/lancamentos'
    | '/outras-receitas'
    | '/outros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cachaca'
    | '/_authenticated/comida'
    | '/_authenticated/dashboard'
    | '/_authenticated/lancamentos'
    | '/_authenticated/outras-receitas'
    | '/_authenticated/outros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cachaca': {
      id: '/_authenticated/cachaca'
      path: '/cachaca'
      fullPath: '/cachaca'
      preLoaderRoute: typeof AuthenticatedCachacaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comida': {
      id: '/_authenticated/comida'
      path: '/comida'
      fullPath: '/comida'
      preLoaderRoute: typeof AuthenticatedComidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outras-receitas': {
      id: '/_authenticated/outras-receitas'
      path: '/outras-receitas'
      fullPath: '/outras-receitas'
      preLoaderRoute: typeof AuthenticatedOutrasReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outros': {
      id: '/_authenticated/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof AuthenticatedOutrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCachacaRoute: typeof AuthenticatedCachacaRoute
  AuthenticatedComidaRoute: typeof AuthenticatedComidaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedOutrasReceitasRoute: typeof AuthenticatedOutrasReceitasRoute
  AuthenticatedOutrosRoute: typeof AuthenticatedOutrosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCachacaRoute: AuthenticatedCachacaRoute,
  AuthenticatedComidaRoute: AuthenticatedComidaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedOutrasReceitasRoute: AuthenticatedOutrasReceitasRoute,
  AuthenticatedOutrosRoute: AuthenticatedOutrosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
